'use strict';
/*
 * ext_fingerprints.js — 扩展高危指纹特征库
 * ---------------------------------------------------------------------------
 * 设计目标：参照 FingerprintHub、wscan-Fingerprint 等开源高危指纹特征库的
 * 收录思路，对企业攻防演练中常见的 Web 中间件 / 框架 / 管理平台 / 大数据组件
 * 进行结构化补充，与 high_risk_fingerprint_db.json 共同构成"高危指纹识别"规则集。
 *
 * 结构约定（与 high_risk_fingerprint_db.json 完全兼容，可直接被 security.js 的
 * matchHighRisk / evaluateRules 复用）：
 *   id            唯一标识
 *   product_cn    中文产品名
 *   category      分类
 *   risk_level    Critical | High | Medium
 *   cvss_base     基准 CVSS
 *   match_rules   命中维度（任一维度命中即算命中，match_type=or）
 *     header_server     Server 响应头包含
 *     header_custom     其它响应头正则（大小写不敏感）
 *     path_keywords     需实际探测 verify_paths 且非 404 才计为命中
 *     body_keywords     响应体包含
 *     cookie_keywords   Set-Cookie 包含
 *     title_keywords    <title> 包含
 *     favicon_mmh3      favicon 的 mmh3 哈希
 *   verify_paths   供 path_keywords 二次确认的路径
 *   critical_vulnerabilities  关联真实 CVE（仅收录已公开确认的高危项）
 *
 * 注：critical_vulnerabilities 仅写入公开确认的真实 CVE，避免虚构编号误导研判。
 */

const EXT_FINGERPRINTS = [
  {
    id: 'EXT-WEBLOGIC-001',
    product_cn: 'Oracle WebLogic Server',
    category: 'Java 应用服务器',
    vendor: 'Oracle',
    risk_level: 'Critical',
    cvss_base: 9.8,
    priority: 1,
    match_type: 'or',
    match_rules: {
      header_server: ['WebLogic'],
      header_custom: [],
      path_keywords: ['/console/login/LoginForm.jsp', '/uddiexplorer/', '/wls-wsat/'],
      body_keywords: ['WebLogic Server', 'BEA WebLogic', '<title>WebLogic'],
      cookie_keywords: ['JSESSIONID'],
      title_keywords: ['WebLogic'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/console/login/LoginForm.jsp', '/wls-wsat/CoordinatorPortType'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2020-14882', vuln_name: 'Console 未授权远程代码执行', type: '远程代码执行', cvss: 9.8, affected_versions: 'WebLogic 10.3.6.0.0, 12.1.3.0.0, 12.2.1.3.0-12.2.1.4.0, 14.1.1.0.0', poc_available: true },
      { cve_id: 'CVE-2017-10271', vuln_name: 'XMLDecoder 反序列化 RCE', type: '远程代码执行', cvss: 9.8, affected_versions: 'WebLogic 10.3.6.0.0, 12.1.3.0.0, 12.2.1.1.0-12.2.1.2.0', poc_available: true },
      { cve_id: 'CVE-2019-2725', vuln_name: 'wls9-async 反序列化 RCE', type: '远程代码执行', cvss: 9.8, affected_versions: 'WebLogic 10.3.6.0.0, 12.1.3.0.0', poc_available: true },
    ],
    affected_versions: 'WebLogic 10.3.6 / 12.1.x / 12.2.x / 14.1.x',
    remediation: '升级至官方安全补丁；限制 /console、/wls-wsat 公网暴露；启用访问白名单',
  },
  {
    id: 'EXT-JENKINS-001',
    product_cn: 'Jenkins CI/CD',
    category: '持续集成平台',
    vendor: 'Jenkins',
    risk_level: 'High',
    cvss_base: 8.8,
    priority: 2,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: ['X-Jenkins'],
      path_keywords: ['/script', '/manage', '/jenkins/script'],
      body_keywords: ['Jenkins', 'Jenkins ver', 'Build History', 'href="/job/'],
      cookie_keywords: ['JSESSIONID', 'jenkins'],
      title_keywords: ['Jenkins'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/script', '/manage', '/login'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2018-1000861', vuln_name: 'Stapler 任意文件读取/RCE', type: '远程代码执行', cvss: 8.8, affected_versions: 'Jenkins <= 2.153, LTS <= 2.138.3', poc_available: true },
      { cve_id: 'CVE-2019-1003000', vuln_name: 'Groovy 沙箱绕过 RCE', type: '远程代码执行', cvss: 8.8, affected_versions: 'Jenkins <= 2.137, 流水线插件', poc_available: true },
      { cve_id: 'CVE-2024-23897', vuln_name: 'CLI 任意文件读取', type: '任意文件读取', cvss: 8.8, affected_versions: 'Jenkins <= 2.441, LTS <= 2.426.2', poc_available: true },
    ],
    affected_versions: 'Jenkins 全系列（含 LTS）',
    remediation: '升级至最新安全版本；禁止 manager/script 接口公网暴露；启用认证与 RBAC',
  },
  {
    id: 'EXT-ACTIVEMQ-001',
    product_cn: 'Apache ActiveMQ',
    category: '消息中间件',
    vendor: 'Apache',
    risk_level: 'Critical',
    cvss_base: 10.0,
    priority: 1,
    match_type: 'or',
    match_rules: {
      header_server: ['ActiveMQ'],
      header_custom: ['Server: ActiveMQ'],
      path_keywords: ['/admin/', '/api/message/'],
      body_keywords: ['ActiveMQ', 'Apache ActiveMQ', 'Welcome to the ActiveMQ'],
      cookie_keywords: ['JSESSIONID'],
      title_keywords: ['ActiveMQ'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/admin/', '/admin/index.jsp'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2023-46604', vuln_name: 'OpenWire 反序列化 RCE', type: '远程代码执行', cvss: 10.0, affected_versions: 'ActiveMQ 5.18.0-5.18.2, 5.17.0-5.17.5, 5.16.0-5.16.6, 5.15.16', poc_available: true },
      { cve_id: 'CVE-2015-5254', vuln_name: 'Serialized 消息反序列化 RCE', type: '远程代码执行', cvss: 9.9, affected_versions: 'ActiveMQ 5.x', poc_available: true },
      { cve_id: 'CVE-2016-3088', vuln_name: 'fileserver 任意文件上传', type: '任意文件上传', cvss: 9.8, affected_versions: 'ActiveMQ 5.x (fileserver 开启)', poc_available: true },
    ],
    affected_versions: 'ActiveMQ 5.15.x / 5.16.x / 5.17.x / 5.18.x',
    remediation: '升级至 5.15.16+/5.16.7+/5.17.6+/5.18.3+；关闭 fileserver；限制 admin 后台',
  },
  {
    id: 'EXT-TOMCAT-001',
    product_cn: 'Apache Tomcat',
    category: 'Java 应用服务器',
    vendor: 'Apache',
    risk_level: 'High',
    cvss_base: 9.8,
    priority: 2,
    match_type: 'or',
    match_rules: {
      header_server: ['Apache-Coyote', 'Tomcat'],
      header_custom: [],
      path_keywords: ['/manager/html', '/host-manager/html', '/examples/'],
      body_keywords: ['Apache Tomcat', 'Tomcat', 'JSPPage'],
      cookie_keywords: ['JSESSIONID'],
      title_keywords: ['Tomcat'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/manager/html', '/host-manager/html'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2020-1938', vuln_name: 'Ghostcat AJP 文件读取/RCE', type: '任意文件读取', cvss: 9.8, affected_versions: 'Tomcat 6/7/8/9 (AJP 开启)', poc_available: true },
      { cve_id: 'CVE-2017-12615', vuln_name: 'PUT 方法任意文件上传', type: '任意文件上传', cvss: 9.8, affected_versions: 'Tomcat 7.0.0-7.0.79', poc_available: true },
      { cve_id: 'CVE-2019-0232', vuln_name: 'CGI Servlet RCE', type: '远程代码执行', cvss: 8.1, affected_versions: 'Tomcat 9.0.0.M1-9.0.17, 8.5.0-8.5.39', poc_available: true },
    ],
    affected_versions: 'Tomcat 7.x / 8.5.x / 9.0.x',
    remediation: '升级至最新版本；关闭 AJP 或限制来源；删除默认 manager/examples',
  },
  {
    id: 'EXT-GITLAB-001',
    product_cn: 'GitLab CE/EE',
    category: '代码托管平台',
    vendor: 'GitLab',
    risk_level: 'Critical',
    cvss_base: 9.9,
    priority: 1,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: ['X-GitLab'],
      path_keywords: ['/users/sign_in', '/admin', '/explore'],
      body_keywords: ['GitLab', 'gitlab-ci', 'GitLab Inc.'],
      cookie_keywords: ['_gitlab_session', 'remember_user_token'],
      title_keywords: ['GitLab'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/users/sign_in', '/admin'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2021-22205', vuln_name: 'ExifTool 反序列化 RCE', type: '远程代码执行', cvss: 9.9, affected_versions: 'GitLab 11.9-13.10.4, 13.9-13.9.7, 13.10-13.10.2', poc_available: true },
      { cve_id: 'CVE-2022-2992', vuln_name: 'GitHub 导入 SSRF/RCE', type: '远程代码执行', cvss: 9.9, affected_versions: 'GitLab 15.1-15.1.4, 15.0.x, 14.10.x', poc_available: true },
    ],
    affected_versions: 'GitLab 11.x-15.x',
    remediation: '升级至官方安全补丁；限制 admin 区公网访问；关闭公开注册',
  },
  {
    id: 'EXT-SOLR-001',
    product_cn: 'Apache Solr',
    category: '搜索引擎',
    vendor: 'Apache',
    risk_level: 'High',
    cvss_base: 9.8,
    priority: 2,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: [],
      path_keywords: ['/solr/admin/cores', '/solr/', '/solr/admin/info/system'],
      body_keywords: ['Apache Solr', 'SolrAdmin', 'lucene'],
      cookie_keywords: [],
      title_keywords: ['Solr'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/solr/admin/cores', '/solr/admin/info/system'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2019-0193', vuln_name: 'DataImportHandler RCE', type: '远程代码执行', cvss: 9.8, affected_versions: 'Solr < 7.7.2, 8.0.0-8.1.1', poc_available: true },
      { cve_id: 'CVE-2017-12629', vuln_name: 'XPath RCE / XXE', type: '远程代码执行', cvss: 9.8, affected_versions: 'Solr 5.5.0-5.5.5, 6.0.0-6.6.2', poc_available: true },
      { cve_id: 'CVE-2023-50386', vuln_name: 'Schema RCE', type: '远程代码执行', cvss: 8.8, affected_versions: 'Solr 8.10.0-8.11.2, 9.0.0-9.3.0', poc_available: true },
    ],
    affected_versions: 'Solr 5.x-9.x',
    remediation: '升级至安全版本；禁用 DataImportHandler；限制 admin 接口公网暴露',
  },
  {
    id: 'EXT-IIS-001',
    product_cn: 'Microsoft IIS',
    category: 'Web 服务器中间件',
    vendor: 'Microsoft',
    risk_level: 'High',
    cvss_base: 9.8,
    priority: 2,
    match_type: 'or',
    match_rules: {
      header_server: ['Microsoft-IIS', 'Microsoft-HTTPAPI'],
      header_custom: [],
      path_keywords: ['/iisstart.htm', '/aspnet_client/', '/powershell/'],
      body_keywords: ['Microsoft-IIS', 'IIS', 'Server Error'],
      cookie_keywords: ['ASPSESSIONID', 'ASP.NET_SessionId'],
      title_keywords: [],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/iisstart.htm', '/aspnet_client/'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2021-31166', vuln_name: 'HTTP.sys 远程代码执行', type: '远程代码执行', cvss: 9.8, affected_versions: 'IIS 10.0 (Windows 10/Server 2019/2004)', poc_available: true },
      { cve_id: 'CVE-2017-7269', vuln_name: 'WebDAV 缓冲区溢出 RCE', type: '远程代码执行', cvss: 9.8, affected_versions: 'IIS 6.0 (Windows Server 2003)', poc_available: true },
    ],
    affected_versions: 'IIS 6.0 / 7.x / 8.x / 10.0',
    remediation: '升级系统补丁；关闭 WebDAV；限制管理端点公网暴露',
  },
  {
    id: 'EXT-KIBANA-001',
    product_cn: 'Kibana',
    category: '数据可视化平台',
    vendor: 'Elastic',
    risk_level: 'High',
    cvss_base: 9.8,
    priority: 2,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: ['kbn-name', 'X-Elastic-Product'],
      path_keywords: ['/app/kibana', '/api/console', '/status'],
      body_keywords: ['Kibana', 'kibana.bundle', 'Elastic'],
      cookie_keywords: ['sid'],
      title_keywords: ['Kibana'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/api/console', '/status'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2019-7609', vuln_name: 'Timelion 原型链 RCE', type: '远程代码执行', cvss: 9.8, affected_versions: 'Kibana < 6.5.2', poc_available: true },
      { cve_id: 'CVE-2023-29441', vuln_name: 'CVE-2023-29441 原型污染 RCE', type: '远程代码执行', cvss: 8.8, affected_versions: 'Kibana 8.0.0-8.6.1', poc_available: true },
    ],
    affected_versions: 'Kibana 6.x / 7.x / 8.x',
    remediation: '升级至安全版本；启用 X-Pack 安全；限制管理端口公网暴露',
  },
  {
    id: 'EXT-GRAFANA-001',
    product_cn: 'Grafana',
    category: '监控可视化平台',
    vendor: 'Grafana Labs',
    risk_level: 'High',
    cvss_base: 7.5,
    priority: 2,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: ['X-Grafana-Org-Id'],
      path_keywords: ['/login', '/api/health', '/dashboard'],
      body_keywords: ['Grafana', 'grafana.', 'Grafana Labs'],
      cookie_keywords: ['grafana_session'],
      title_keywords: ['Grafana'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/api/health', '/login'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2021-43798', vuln_name: '路径穿越读取任意文件', type: '任意文件读取', cvss: 7.5, affected_versions: 'Grafana 8.0.0-8.3.0', poc_available: true },
      { cve_id: 'CVE-2020-13379', vuln_name: 'SSRF/任意用户枚举', type: '服务端请求伪造', cvss: 6.1, affected_versions: 'Grafana 3.1-7.4.5', poc_available: true },
    ],
    affected_versions: 'Grafana 3.x-8.x',
    remediation: '升级至安全版本；限制管理端口公网暴露；启用认证',
  },
  {
    id: 'EXT-SONARQUBE-001',
    product_cn: 'SonarQube',
    category: '代码质量平台',
    vendor: 'SonarSource',
    risk_level: 'Medium',
    cvss_base: 7.5,
    priority: 3,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: ['X-Sonar-', 'Server: SonarQube'],
      path_keywords: ['/projects', '/api/system/status', '/sessions/new'],
      body_keywords: ['SonarQube', 'sonar.', 'Code Quality'],
      cookie_keywords: ['SONARQUBE'],
      title_keywords: ['SonarQube'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/api/system/status', '/sessions/new'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2020-27986', vuln_name: 'API 未授权访问（信息泄露）', type: '未授权访问', cvss: 7.5, affected_versions: 'SonarQube 默认配置（匿名可访问 API）', poc_available: true },
    ],
    affected_versions: 'SonarQube 全系列（默认匿名可读）',
    remediation: '关闭匿名访问（sonar.allowAnonymousAccess=false）；限制公网暴露',
  },
  {
    id: 'EXT-ZOOKEEPER-001',
    product_cn: 'Apache Zookeeper',
    category: '分布式协调服务',
    vendor: 'Apache',
    risk_level: 'Medium',
    cvss_base: 6.5,
    priority: 3,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: [],
      path_keywords: [],
      body_keywords: ['Zookeeper version', 'Environment:'],
      cookie_keywords: [],
      title_keywords: [],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: [],
    critical_vulnerabilities: [
      { cve_id: 'ZK-UNAUTH', vuln_name: '未授权访问（可读取/写入节点配置）', type: '未授权访问', cvss: 6.5, affected_versions: 'Zookeeper 默认无 ACL', poc_available: true },
    ],
    affected_versions: 'Zookeeper 3.x（默认配置）',
    remediation: '配置 ACL / SASL 认证；通过防火墙限制 2181 端口',
  },
  {
    id: 'EXT-YARN-001',
    product_cn: 'Hadoop YARN ResourceManager',
    category: '大数据调度平台',
    vendor: 'Apache',
    risk_level: 'High',
    cvss_base: 8.8,
    priority: 1,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: [],
      path_keywords: ['/cluster/cluster', '/ws/v1/cluster/apps', '/cluster/apps'],
      body_keywords: ['Hadoop', 'ResourceManager', 'YARN', 'ApplicationMaster'],
      cookie_keywords: [],
      title_keywords: ['Hadoop'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/ws/v1/cluster/apps', '/cluster/cluster'],
    critical_vulnerabilities: [
      { cve_id: 'YARN-UNAUTH', vuln_name: 'REST API 未授权（可提交恶意 Container）', type: '未授权访问', cvss: 8.8, affected_versions: 'Hadoop YARN 默认无认证', poc_available: true },
    ],
    affected_versions: 'Hadoop 2.x / 3.x（默认配置）',
    remediation: '启用 Kerberos 认证；限制 8088 端口公网暴露',
  },
  {
    id: 'EXT-K8S-001',
    product_cn: 'Kubernetes API Server',
    category: '容器编排平台',
    vendor: 'CNCF',
    risk_level: 'Critical',
    cvss_base: 9.8,
    priority: 1,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: ['WWW-Authenticate: Basic realm="kubernetes"', 'content-type: application/json'],
      path_keywords: ['/api', '/apis', '/healthz'],
      body_keywords: ['kubernetes', 'Unauthorized', 'kind:'],
      cookie_keywords: [],
      title_keywords: [],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/healthz', '/api'],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2018-1002105', vuln_name: 'API Server 提权（未授权提升为 admin）', type: '权限绕过', cvss: 9.8, affected_versions: 'Kubernetes 1.10-1.12', poc_available: true },
      { cve_id: 'CVE-2019-1002100', vuln_name: 'kubectl cp 任意文件写入', type: '任意文件写入', cvss: 7.5, affected_versions: 'Kubernetes 1.11-1.13', poc_available: true },
    ],
    affected_versions: 'Kubernetes 1.x（认证配置不当易未授权）',
    remediation: '强制启用 RBAC 与证书认证；禁止匿名访问 /api；限制 6443 端口',
  },
  {
    id: 'EXT-SCM-EXPOSE-001',
    product_cn: '版本控制元数据泄露（.git/.svn）',
    category: '信息泄露',
    vendor: '通用',
    risk_level: 'High',
    cvss_base: 7.5,
    priority: 2,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: [],
      path_keywords: ['.git/config', '.svn/entries', '.git/HEAD'],
      body_keywords: ['[core]', 'repositoryformatversion', 'svn:',
        '<?xml version="1.0" encoding="utf-8"?>'],
      cookie_keywords: [],
      title_keywords: [],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['.git/HEAD', '.svn/entries', '.git/config'],
    critical_vulnerabilities: [
      { cve_id: 'SCM-DIR-EXPOSE', vuln_name: '源码仓库目录暴露（可还原完整源码）', type: '信息泄露', cvss: 7.5, affected_versions: '部署遗漏 .git/.svn 目录的站点', poc_available: true },
    ],
    affected_versions: '通用 Web 部署',
    remediation: '删除站点根目录下的 .git/.svn；部署前清理版本控制元数据',
  },
  {
    id: 'EXT-SWAGGER-001',
    product_cn: 'Swagger / OpenAPI 文档暴露',
    category: '信息泄露',
    vendor: '通用',
    risk_level: 'Medium',
    cvss_base: 5.3,
    priority: 3,
    match_type: 'or',
    match_rules: {
      header_server: [],
      header_custom: [],
      path_keywords: ['/swagger-ui.html', '/v2/api-docs', '/swagger/index.html', '/api-docs'],
      body_keywords: ['Swagger UI', 'swagger.json', 'OpenAPI', 'swagger-config'],
      cookie_keywords: [],
      title_keywords: ['Swagger'],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: ['/swagger-ui.html', '/v2/api-docs', '/swagger/index.html'],
    critical_vulnerabilities: [
      { cve_id: 'API-DOCS-EXPOSE', vuln_name: 'API 文档未授权暴露（泄露接口与参数）', type: '信息泄露', cvss: 5.3, affected_versions: '开启 Swagger 且未鉴权的站点', poc_available: true },
    ],
    affected_versions: 'Spring Boot / 各类框架默认开启 Swagger',
    remediation: '生产环境关闭 Swagger；对文档端点加鉴权',
  },
  {
    id: 'EXT-NGINX-001',
    product_cn: 'Nginx',
    category: 'Web 服务器中间件',
    vendor: 'Nginx/F5',
    risk_level: 'Medium',
    cvss_base: 7.5,
    priority: 3,
    match_type: 'or',
    match_rules: {
      header_server: ['nginx'],
      header_custom: [],
      path_keywords: [],
      body_keywords: ['nginx', 'Welcome to nginx'],
      cookie_keywords: [],
      title_keywords: [],
      favicon_mmh3: [],
      favicon_md5: [],
    },
    verify_paths: [],
    critical_vulnerabilities: [
      { cve_id: 'CVE-2019-9511', vuln_name: 'HTTP/2 资源耗尽（DoS）', type: '拒绝服务', cvss: 7.5, affected_versions: 'Nginx 1.9.5-1.17.2 (HTTP/2)', poc_available: true },
      { cve_id: 'CVE-2017-7529', vuln_name: 'Range 过滤器整数溢出（越界读取）', type: '任意文件读取', cvss: 7.5, affected_versions: 'Nginx 0.5.6-1.13.2', poc_available: true },
    ],
    affected_versions: 'Nginx 1.x（旧版本）',
    remediation: '升级至最新稳定版；关注配置安全（alias 穿越、目录列表）',
  },
];

module.exports = { EXT_FINGERPRINTS };
